# Managed by the HY-chat ECS deployment.
server {
  set $forward_scheme http;
  set $server "hy-chat-api";
  set $port 8000;

  listen 80;
  listen [::]:80;
  server_name api.hy-ai.xyz;

  access_log /data/logs/hy-chat-api_access.log proxy;
  error_log /data/logs/hy-chat-api_error.log warn;

  include conf.d/include/block-exploits.conf;

  location / {
    include conf.d/include/proxy.conf;
  }

  include /data/nginx/custom/server_proxy[.]conf;
}
