# File I/O
BYTES_PER_KIBIBYTE = 1024
BYTES_PER_MEBIBYTE = 1024 * 1024
FILE_IO_CHUNK_BYTES = BYTES_PER_MEBIBYTE
DEFAULT_UPLOAD_MAX_BYTES = 50 * BYTES_PER_MEBIBYTE

# Service ports
API_SERVER_DEFAULT_PORT = 8000
AGENT_SERVER_DEFAULT_PORT = 2024


# Agent runs
DEFAULT_AGENT_RUN_LIST_LIMIT = 20
DEFAULT_AGENT_RUN_STATUS_TTL_SECONDS = 60 * 60

# Image generation
DEFAULT_IMAGE_API_TIMEOUT_SECONDS = 120.0
DEFAULT_IMAGE_DOWNLOAD_TIMEOUT_SECONDS = 120.0
DEFAULT_IMAGE_PROMPT_MAX_LENGTH = 32_000
DEFAULT_IMAGE_INPUT_MAX_BYTES = 50 * BYTES_PER_MEBIBYTE
DEFAULT_STORED_IMAGE_LIST_LIMIT = 20
MAX_STORED_IMAGE_LIST_LIMIT = 100

# Tracing
DEFAULT_TRACE_PAYLOAD_MAX_CHARS = 12_000

# Cache TTLs
WEB_SEARCH_CACHE_TTL_SECONDS = 5 * 60
WEATHER_CACHE_TTL_SECONDS = 10 * 60
STOCK_CACHE_TTL_SECONDS = 60

# Supported image formats
SUPPORTED_IMAGE_CONTENT_TYPES = frozenset({"image/jpeg", "image/png", "image/webp"})
SUPPORTED_IMAGE_EXTENSIONS = frozenset({".jpg", ".jpeg", ".png", ".webp"})
